apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: simple-node-travis
        image: aluminetchidiebre/simple-node-travis
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
        env:
        - name: FAVORITE_FOOD  # or you can specify them in a k8s ConfigMap when you have many any you want to have them referenced in to many pods in thesame cluster
          value: "ogbono"
